# Generated by Django 3.0.8 on 2020-07-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('dataNascimento', models.DateField(max_length=10)),
                ('tipoTeste', models.CharField(max_length=20)),
                ('resultado', models.CharField(max_length=15)),
            ],
        ),
    ]
